# Configure nixpacks to use Dockerfile
[phases.setup]
nixPkgs = ['docker']

[phases.build]
cmds = ['docker build -t app .']

[phases.start]
cmd = './Gateway serve --env production --hostname 0.0.0.0 --port $PORT'