# Direct Swift build with nixpacks
[phases.setup]
nixPkgs = ['swift', 'pkg-config', 'openssl']

[phases.install]
cmds = ['swift package resolve']

[phases.build]  
cmds = ['swift build --configuration release']

[phases.start]
cmd = './.build/release/Gateway serve --env production --hostname 0.0.0.0 --port $PORT'