# Railway 프로젝트 설정
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "./Gateway serve --env production --hostname 0.0.0.0 --port $PORT"

# 환경별 설정
[environments.production]
variables = {}

[environments.staging] 
variables = {}

# 서비스별 설정은 Railway 대시보드에서 개별 설정