name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Railway CLI
      uses: railway/cli@v3
      with:
        command: deploy
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}